num_requests: 10
output_folder: "results"
cds_request:
cams_request:
  name: cams-europe-air-quality-reanalyses
  request: {
            'level': '0',
            'model': 'ensemble',
            'type': 'interim_reanalysis',
            'year': '2023',
            'month': '01',
            'format': 'zip',
            'variable': 'particulate_matter_10um'
            }
cams_netcdf4_request:
  name: cams-europe-air-quality-reanalyses
  request: {
            'level': '0',
            'model': 'ensemble',
            'type': 'interim_reanalysis',
            'year': '2023',
            'month': '01',
            'format': 'netcdf4',
            'variable': 'particulate_matter_10um'
            }