num_requests: 10
output_folder: "results"
cds_request:
  name: reanalysis-era5-single-levels
  request: {
            "variable": [
            '10m_u_component_of_wind', '10m_v_component_of_wind'],
            "product_type": "reanalysis",
            "year": "2020",
            "month": "05",
            "day": ["01",
            "01", "02", "03",
            '04', '05', '06',
            '07', '08', '09',
            '10', '11', '12',
            '13', '14', '15',
            '16', '17', '18',
            '19', '20', '21',
            '22', '23', '24',
            '25', '26', '27',
            '28', '29', '30',
            '31',
            ],
            'time': [ '00:00'
            # '00:00','01:00','02:00',
            # '03:00', '04:00', '05:00',
            # '06:00', '07:00', '08:00',
            # '09:00', '10:00', '11:00',
            # '12:00', '13:00', '14:00',
            # '15:00', '16:00', '17:00',
            # '18:00', '19:00', '20:00',
            # '21:00','22:00','23:00'
        ],
            "format": "grib"
            }

gcp_request:
    url_dataset: gs://gcp-public-data-arco-era5/ar/1959-2022-full_37-1h-0p25deg-chunk-1.zarr-v2
    start: 2020-05-01T00
    end: 2020-05-31T00
    frequence: "D"
    variables: ["10m_u_component_of_wind","10m_v_component_of_wind"]

microsoft:
    url_dataset: https://planetarycomputer.microsoft.com/api/stac/v1/
    start: "2020-05-01"
    end: "2020-05-31"
    frequence: "D"
    variables: ["northward_wind_at_10_metres","eastward_wind_at_10_metres"]
